version: "3.1"

services:
  scheduler:
    build: .
    image: daskdocker
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build: .
    image: daskdocker
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]